# Generated by Django 2.2.28 on 2022-11-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addresskdlfypadhh'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresskdlfypadhh',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
